title: Definiti
description: Definitively your model Definition
theme: minima
baseurl: "/"
url: "https://definiti.github.io"

github:
  repository_url: https://github.com/definiti/definiti
  repository_name: Definiti
  project_tagline: Definitively your model Definition
  owner_url: https://github.com/definiti
  owner_name: Definiti

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass